package model.enums;

public enum Material {
    B_CONCRETE, FZ_FIBRE_CEMENT, GG_GREY_CAST, GGG_DUCTILE_IRONT,
    MA_BRICKWORK, PE_POLYETHYLENE_WELDED, PE_POLYETHYLENE , PP_POLYPROPELENE, PVC_POLYVINYLCHLORID,
    SB_REINFORCED_CONCRETE, STZ_STONEWARE, THIN_WALLED, OTHER
    
}
